--Cuantos libros ha escrito o colaborado cierto autor (AUTOR CON ID 1)
SELECT * FROM AUTORES;

SELECT COUNT(l.ID_AUTOR) AS CANTLIBROS,a.NOMBRE
 FROM LIBROS l INNER JOIN AUTORES a 
ON l.ID_AUTOR = a.ID_AUTOR
AND a.ID_AUTOR IN ( 1,2)

GROUP BY a.NOMBRE


--Cuantos libros ha editado una casa editora (EDITORIAL CoN ID 1)

SELECT COUNT (E.ID_EDITORA) AS LIBROSEDITORA,A.NOMBRE
FROM LIBROS E INNER JOIN EDITORAS A
ON E.ID_EDITORA = A.ID_EDITORA
GROUP BY A.NOMBRE

--Cantidad de autores por libro

SELECT COUNT (I.ID_AUTOR) AS AUTORESPORLIBROS, i.TITULO
FROM LIBROS i INNER JOIN AUTORES r
ON i.ID_AUTOR = r.ID_AUTOR
GROUP BY i.TITULO

--Con cuales autores ha trabajado una casa editora


 SELECT a.ID_AUTOR, a.NOMBRE,a.APELLIDO, e.NOMBRE AS TRABAJOEN 
 FROM AUTORES a,EDITORAS e,LIBROS l
 WHERE a.ID_AUTOR = l.ID_AUTOR AND l.ID_EDITORA = e.ID_EDITORA 
 GROUP BY a.ID_AUTOR, a.NOMBRE,a.APELLIDO, e.NOMBRE

 --Con cuales autores NO ha trabajado una casa editora(ID = 2)

 SELECT a.NOMBRE,a.APELLIDO, e.NOMBRE AS NOTRABAJOEN
 FROM AUTORES a, LIBROS l,EDITORAS e
 WHERE  l.ID_EDITORA = e.ID_EDITORA
   AND l.ID_AUTOR NOT IN (SELECT l2.ID_AUTOR 
							FROM LIBROS l2, EDITORAS e2, AUTORES a2 
						   WHERE l2.ID_EDITORA = 2
							 AND l2.ID_EDITORA = e2.ID_EDITORA
							 AND l2.ID_AUTOR = a2.ID_AUTOR)
   AND l.ID_AUTOR = a.ID_AUTOR;

 SELECT  * FROM LIBROS

 


