CREATE DATABASE PRE_DASE_DATOSWED;

USE PRE_DASE_DATOSWED;

--CREACION DE LA TABLA EDITORIAL

CREATE TABLE EDITORAS (
ID_EDITORA INT IDENTITY PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(20)NOT NULL,
ANOFUNDACION DATE NOT NULL,
FUNDADORA VARCHAR(50)NOT NULL, 
)
--CREACION DE LA TABLA LIBROS

CREATE TABLE LIBROS(
ID INT IDENTITY PRIMARY KEY NOT NULL,
TITULO VARCHAR (20) NOT NULL,
ANOPUBLICACION DATE NOT NULL,
ID_EDITORA INT NOT NULL,
ID_AUTOR INT NOT NULL,
)

--CREACION DE LA TABLA AUTORES

CREATE TABLE AUTORES(
ID_AUTOR INT IDENTITY PRIMARY KEY NOT NULL,
NOMBRE VARCHAR (20) NOT NULL,
APELLIDO VARCHAR (20) NOT NULL,
FECHANACIMIENTO DATE NOT NULL,
PAIS VARCHAR (20)NOT NULL ,
)

-- RELACION ENTRE LA TABLA LIBROS y LA TABLA EDITORA 
ALTER TABLE LIBROS ADD CONSTRAINT FK_LibroEditora
FOREIGN KEY (ID_EDITORA) REFERENCES EDITORAS (ID_EDITORA)

-- RELACION ENTRE LA TABLA LIBRO Y LA TABLA AUTORES

ALTER TABLE LIBROS ADD CONSTRAINT FK_LibroAutor
FOREIGN KEY (ID_AUTOR) REFERENCES AUTORES (ID_AUTOR)

